import React, { useState, useEffect } from "react";
import "./App.css";
import jsPDF from "jspdf";

function App() {
  const prompts = [
    "What made you smile today?",
    "Describe your ideal day. What would it look like?",
    "Write a letter to your future self.",
    "What is something you’ve always wanted to try but haven’t yet?",
    "What would you do if you had one extra hour every day?",
    "What is a place you feel completely at peace?",
    "Describe a time when you felt truly alive.",
    "Write about a challenge you overcame and what you learned from it.",
    "What are three things you’re grateful for today?",
    "If you could talk to your past self, what advice would you give?",
    "What’s the best advice you’ve ever received?",
    "What does success mean to you?",
    "Write about a dream you had recently.",
    "What makes you feel most connected to the world?",
    "If you could live anywhere in the world, where would it be?",
    "What’s one small thing that makes you happy every day?",
    "What are your most cherished childhood memories?",
    "What are you afraid of, and why?",
    "If you could have dinner with anyone in the world, dead or alive, who would it be?",
    "What book or movie has had the greatest impact on your life?",
    "Write about a time you felt misunderstood.",
    "What would you do if you couldn’t fail?",
    "What’s your greatest achievement?",
    "How do you handle failure?",
    "Write a letter to someone who changed your life.",
    "What’s your biggest regret, and how would you change it?",
    "What is your dream job?",
    "Write about something you’ve learned the hard way.",
    "What does your perfect weekend look like?",
    "What are your non-negotiables in life?",
    "Describe your most meaningful friendship.",
    "What would you do with a million dollars?",
    "What motivates you to get out of bed in the morning?",
    "If you could visit any country, where would you go and why?",
    "How do you handle stress?",
    "What makes you unique?",
    "What would you tell your younger self?",
    "Write about a time you took a risk and it paid off.",
    "What’s your favorite form of self-care?",
    "What’s the best compliment you’ve ever received?",
    "What’s the biggest lesson you’ve learned so far?",
    "What are the most important things in life to you?",
    "Describe a moment of serendipity in your life.",
    "What would your perfect day look like?",
    "Write about a time when you felt proud of yourself.",
    "What’s your greatest fear and how do you overcome it?",
    "What’s your most important value?",
    "How do you define happiness?",
    "What’s the best decision you’ve ever made?",
    "What’s your favorite hobby and why?",
    "If you could master any skill instantly, what would it be?",
    "What’s one thing you wish you knew earlier in life?",
    "Describe a person who has inspired you.",
    "What would you do if you weren’t afraid?",
    "What’s the best gift you’ve ever given?",
    "Write about a place you’ve always wanted to visit.",
    "What’s something new you’ve learned recently?",
    "What was the last risk you took?",
    "Write about a memory you associate with a specific smell.",
    "What’s something that always cheers you up?",
    "How do you feel about change?",
    "What’s your favorite quote, and why?",
    "Describe the perfect morning routine.",
    "What’s a skill you want to improve?",
    "Write about a time when you overcame an obstacle.",
    "If you could go back in time, what period would you visit?",
    "What are the most important lessons you’ve learned from your mistakes?",
    "What’s one thing you would like to change in the world?",
    "What’s your favorite type of music and why?",
    "Write about a time when you helped someone.",
    "What’s the most beautiful place you’ve ever been to?",
    "What’s something you’ve always been passionate about?",
    "How do you stay motivated?",
    "What’s your idea of a perfect vacation?",
    "What would you do if you were invisible for a day?",
    "What’s the most interesting place you’ve ever visited?",
    "What’s the best meal you’ve ever eaten?",
    "What’s one habit you’d like to break?",
    "What are you most proud of about your upbringing?",
    "What is something you would like to achieve in the next year?",
    "How do you stay productive?",
    "What’s the most valuable thing you own?",
    "What’s something that makes you feel safe?",
    "What’s the best thing about being alive right now?",
    "What’s something you’ve always wanted to learn but never had the time for?",
    "What’s the most fun thing you did this year?",
    "Write about a dream you have for the future.",
    "What’s something you’re really good at?",
    "What does your ideal life look like in 5 years?",
    "What are you most excited about for the future?",
    "Write about a time when you felt truly at peace.",
    "What does friendship mean to you?",
    "How do you practice mindfulness?",
    "Write about a lesson you learned from nature.",
    "What’s the biggest challenge you’ve faced in the past year?",
    "What’s one thing you want to improve about yourself?",
    "What does freedom mean to you?",
    "What makes you feel creative?",
    "How do you define success?",
    "What’s your favorite way to unwind after a busy day?",
    "Describe the moment you realized you had grown up.",
    "What’s the most recent act of kindness you’ve witnessed?",
    "How do you practice gratitude?",
    "What’s the best advice you could give to someone in need?",
    "What would you do if you knew you couldn’t fail?",
    "What’s your idea of the perfect day?",
    "What makes you feel empowered?",
    "What’s something you’ve always wanted to do but haven’t yet?",
    "How do you stay focused on your goals?",
    "What’s your greatest source of inspiration?",
    "What does self-care look like for you?",
    "What’s the most valuable lesson you’ve learned in life?",
    "How do you handle disappointment?",
    "What’s something you would like to experience in life?",
    "How do you find balance in your life?",
    "What’s the best thing you’ve learned from a failure?",
    "What are you most thankful for today?",
    "What’s your favorite season and why?",
    "What’s your happiest memory?",
    "What does it mean to be successful?",
    "What’s one thing you want to do before you die?",
    "Describe a time you took a leap of faith.",
    "What’s something that has shaped your perspective on life?",
    "How do you feel about change in your life?",
    "What is your greatest strength?",
    "What’s the most important thing to you in relationships?",
    "What’s something you wish you could tell your younger self?",
    "What’s your favorite thing about your personality?",
    "What makes you feel proud of yourself?",
    "How do you nurture your mental health?",
    "What’s one thing you’re looking forward to?",
    "What’s something you’ve learned from a mentor?",
    "How do you stay grounded?",
    "What’s the best piece of advice you’ve ever given?",
    "What does love mean to you?",
    "What’s one of your favorite books and why?",
    "What does a balanced life look like to you?",
    "What’s one thing you would tell someone who’s struggling?",
    "What’s a goal you’re working towards?",
    "What are you doing to take care of your mind and body?",
    "How do you handle challenges in life?",
    "Write about your favorite memory of a family gathering.",
	    "What are you most passionate about right now?",
    "Describe a place where you feel most yourself.",
    "What do you consider your biggest accomplishment?",
    "Write a letter to someone who has impacted your life.",
    "What’s something you’re currently working on improving about yourself?",
    "What’s a recent challenge that made you grow?",
    "What does love look like to you?",
    "What’s one thing you’ve always wanted to do but haven’t yet?",
    "Describe a time when you felt completely at peace.",
    "If you could go anywhere in the world, where would it be?",
    "What do you think about when you’re alone?",
    "What would you do if you had more free time?",
    "What is your favorite childhood memory?",
    "Write about a moment you felt truly alive.",
    "What is one thing you’d like to change about the world?",
    "What’s your definition of success?",
    "What has been the biggest turning point in your life?",
    "What are you most grateful for right now?",
    "If you could relive one day of your life, which would it be?",
    "What makes you feel inspired?",
    "What would your perfect day look like?",
    "Write about something you’re afraid of.",
    "What are the three most important things to you in life?",
    "What is your favorite book, and why?",
    "Describe a perfect weekend for you.",
    "Write about a time when you had to make a tough decision.",
    "What is one habit you’d like to develop?",
    "How do you deal with stress?",
    "What’s your favorite way to unwind after a busy day?",
    "If you could spend an hour with anyone, who would it be?",
    "What does happiness look like to you?",
    "What’s something you would never give up?",
    "Write about a time when you helped someone in need.",
    "What does family mean to you?",
    "How do you show love to others?",
    "What’s the most valuable lesson you’ve learned in life?",
    "If you could change one thing about yourself, what would it be?",
    "What would you do with a million dollars?",
    "Write about your dream job.",
    "What is the most beautiful thing you’ve ever seen?",
    "What does a balanced life look like to you?",
    "What’s the best advice you’ve ever received?",
    "What’s your favorite season and why?",
    "What would your ideal vacation be like?",
    "What’s something you learned recently?",
    "What’s your biggest goal right now?",
    "What does it mean to be truly free?",
    "Write about a time you took a risk.",
    "What’s something you’ve been procrastinating on?",
    "How do you keep yourself motivated?",
    "What’s one thing you’d like to improve in your life?",
    "Describe the person who has influenced you the most.",
    "What are you most proud of?",
    "What are you looking forward to this week?",
    "Write about a mistake you learned from.",
    "What’s something that makes you laugh every time?",
    "What does being successful mean to you?",
    "How do you practice gratitude?",
    "What’s something you’re working towards in the next month?",
    "What’s your favorite quote and why?",
    "What’s something you’ve always wanted to learn?",
    "What’s the best compliment you’ve ever received?",
    "What does friendship mean to you?",
    "How do you feel about your current situation in life?",
    "What’s your favorite form of self-care?",
    "What does a fulfilling life look like to you?",
    "What is your favorite childhood book?",
    "What’s something you’ve been proud of recently?",
    "What is one thing that always makes you feel better?",
    "How do you handle setbacks in life?",
    "What’s something you learned from your parents?",
    "Write about a time when you felt out of your comfort zone.",
    "What’s your favorite place in your hometown?",
    "If you could only eat one thing for the rest of your life, what would it be?",
    "How do you define your personal values?",
    "What’s the best decision you’ve ever made?",
    "What is your favorite way to spend a Sunday?",
    "What’s something you’ve achieved that you’re proud of?",
    "What’s a lesson you learned from a past relationship?",
    "How do you stay motivated when things get tough?",
    "Write about a time when you learned something new.",
    "What does personal growth mean to you?",
    "What would you tell your younger self?",
    "How do you cope with disappointment?",
    "What’s one thing you’ve been meaning to do but haven’t yet?",
    "What’s your favorite way to express creativity?",
    "What’s something you enjoy doing alone?",
    "If you could change one thing about the world, what would it be?",
    "What’s your idea of a perfect day off?",
    "What’s something you’re really passionate about?",
    "Write about your best friend.",
    "How do you like to spend your evenings?",
    "What are you grateful for in this moment?",
    "What’s something you’ve done that you thought you couldn’t?",
    "What’s your favorite memory of a family vacation?",
    "What’s one of the most beautiful things you’ve ever heard?",
    "How do you define happiness?",
    "What does it mean to live in the present moment?",
    "What’s the best way you’ve found to relax?",
    "What do you wish you could change about your daily routine?",
    "What are you most looking forward to this year?",
    "What’s something you’ve learned from a mentor?",
    "What’s one way you want to grow in the next year?",
    "Write about a time when you felt truly understood.",
    "How do you deal with negative thoughts?",
    "What’s the most thoughtful gift you’ve ever given?",
    "Write about something you’ve accomplished that you didn’t think you could.",
    "What’s something you love about your personality?",
    "What’s something you want to do this month that will make you proud?",
    "What does self-care look like to you?",
    "What’s your favorite childhood game?",
    "How do you deal with failure?",
    "What’s something you’d like to say to someone who’s hurt you?",
    "What’s the most beautiful thing you’ve learned about yourself?",
    "What’s one thing you’re grateful for today?",
    "What would you do if you knew you couldn’t fail?",
	    "What’s one thing you wish you could do better?",
    "Describe a time when you felt completely empowered.",
    "What’s one thing you’ve learned about yourself recently?",
    "Write about a place that always makes you feel calm.",
    "What is something you feel excited about right now?",
    "What’s one lesson you want to teach your future self?",
    "What’s something you’ve done that you never thought you would?",
    "If you had to choose one word to describe your life, what would it be?",
    "What’s something you’ve struggled with and how did you overcome it?",
    "What does resilience mean to you?",
    "Write about a time when you had to trust someone completely.",
    "How do you stay true to yourself in challenging situations?",
    "What’s something that makes you feel deeply connected to others?",
    "If you could write a letter to your future self, what would you say?",
    "What are the little things that bring you joy?",
    "What is something you admire in others and want to cultivate in yourself?",
    "What’s your favorite way to stay active?",
    "How do you celebrate your achievements?",
    "What is something you’re passionate about that others might not know?",
    "What is a challenge you’re currently facing, and how can you address it?",
    "What do you value most in your friendships?",
    "Write about a time you helped someone without expecting anything in return.",
    "What’s your most memorable travel experience?",
    "How do you define peace?",
    "What’s one thing you’re working on improving in your daily routine?",
    "What would your dream life look like 10 years from now?",
    "Write about a person who has made a big impact on your life.",
    "How do you express gratitude?",
    "What’s something you’ve learned from your mistakes?",
    "What’s a belief that has shaped who you are today?",
    "How do you navigate change in your life?",
    "What are the most important values that guide you?",
    "What’s your definition of inner strength?",
    "What’s the biggest risk you’ve ever taken?",
    "How do you handle uncertainty?",
    "What’s something you’d like to change about your daily habits?",
    "What’s a memory that always makes you smile?",
    "Write about a time when you had to make a difficult choice.",
    "What’s something you’re afraid to do, but really want to try?",
    "What’s one of the most important things you’ve learned about love?",
    "How do you practice mindfulness in your daily life?",
    "What’s something that always brings you peace of mind?",
    "What’s a challenge you’ve recently overcome?",
    "If you could be known for one thing, what would it be?",
    "What would you tell someone who is going through a tough time?",
    "How do you feel about the concept of fate?",
    "What’s your favorite way to unwind and relax?",
    "What’s something you’ve learned about happiness?",
    "How do you stay grounded during stressful situations?",
    "What’s something that’s been on your mind lately?",
    "Write about a time you stood up for something you believe in.",
    "What’s your favorite memory of a family gathering?",
    "How do you express love to the people you care about?",
    "What does personal growth look like to you?",
    "Write about a dream you have for your future.",
    "What’s one habit you’ve been trying to break?",
    "What’s something you’re really proud of accomplishing?",
    "Write about a time when you felt completely at peace.",
    "What’s something you love about yourself?",
    "What’s something you’ve always wanted to do, but have been afraid to try?",
    "What does success look like for you?",
    "What’s the best advice you’ve ever received?",
    "How do you handle setbacks and challenges?",
    "What’s one thing you’ve done that changed your perspective?",
    "What does authenticity mean to you?",
    "Write about a time when you felt truly understood.",
    "How do you like to spend time with others?",
    "What’s your definition of self-love?",
    "What would you do if you knew you couldn’t fail?",
    "What’s your favorite memory from the past year?",
    "What does your ideal weekend look like?",
    "What is one thing you’ve learned about your emotions?",
    "How do you nurture your creativity?",
    "What’s the biggest change you’ve made in the past year?",
    "What does your dream career look like?",
    "What’s something that inspires you every day?",
    "How do you recharge after a busy week?",
    "What’s something you wish you had more time for?",
    "What’s the best decision you’ve made this year?",
    "Write about a time when you faced your fears.",
    "What’s something that you’re deeply grateful for?",
    "What’s your idea of a perfect day?",
    "What’s the most meaningful compliment you’ve received?",
    "What’s something that always makes you laugh?",
    "How do you stay motivated when things are tough?",
    "What does self-care look like for you?",
    "What’s a belief you hold that has shaped your actions?",
    "What are you most looking forward to this month?",
    "How do you stay positive when faced with challenges?",
    "What’s something you’ve learned from a past relationship?",
    "Write about something that made you happy recently.",
    "What’s something you’ve been meaning to do, but keep putting off?",
    "How do you define success in your personal life?",
    "Write about a moment when you felt truly free.",
    "What’s one thing you wish you knew earlier in life?",
    "What’s the most adventurous thing you’ve ever done?",
    "How do you stay true to your values in difficult situations?",
    "What are the things you want to accomplish in the next year?",
    "What’s something you appreciate about your current stage in life?",
    "What’s a skill you’d like to develop?",
    "What does it mean to live with intention?",
    "What is one thing you’ve done that you didn’t think you could?",
    "Write about a time when you felt truly alive.",
    "What’s something you’re working towards right now?",
    "What’s one thing you’ve always wanted to learn?",
    "How do you define your purpose?",
    "What’s something that brings you inner peace?",
    "What’s the most significant challenge you’ve faced in your life?",
    "What’s one thing you could do to make your life easier?",
    "What’s your definition of happiness?",
	"What is the most important lesson you've learned in the last year?",
    "If you could be any age for a week, what age would you be and why?",
    "What’s a personal achievement you are incredibly proud of?",
    "What’s one thing that challenges you every day?",
    "What’s a small act of kindness you did recently?",
    "How do you define true friendship?",
    "What’s something you’ve always wanted to tell someone, but never did?",
    "What’s a passion of yours you don’t share with many people?",
    "What makes you feel seen and heard?",
    "What does your ideal future self look like?",
    "What’s something you wish others knew about you?",
    "What’s your favorite memory from a family celebration?",
    "What’s something you’d like to accomplish in the next six months?",
    "How do you define peace of mind?",
    "What’s one thing you’ve changed your mind about recently?",
    "What’s a random act of kindness you’ve witnessed?",
    "What’s one decision you’ve made that altered the course of your life?",
    "What’s something that always makes you feel confident?",
    "What’s the best compliment you could receive?",
    "What would you like to be remembered for?",
    "What’s your favorite way to stay grounded?",
    "What are you most proud of about the person you’ve become?",
    "What’s your definition of self-respect?",
    "What’s one thing you want to change in your daily routine?",
    "What does home feel like to you?",
    "What’s the most valuable advice you’ve ever given?",
    "How do you deal with feelings of overwhelm?",
    "What’s a recent event that made you feel alive?",
    "What’s one thing you admire about someone close to you?",
    "What’s a book that changed your perspective on life?",
    "What does true independence mean to you?",
    "What’s a time you found beauty in an unexpected place?",
    "How do you practice forgiveness?",
    "What’s one fear you’ve overcome?",
    "What is your greatest source of inspiration?",
    "What’s the best decision you’ve made regarding your mental health?",
    "What are three things that make you feel at peace?",
    "What’s one thing you love about your daily routine?",
    "Write about a time when you took a leap of faith.",
    "What’s something you’ve learned to appreciate about life?",
    "What’s a significant change you’ve made in the last year?",
    "What’s something you love about the present moment?",
    "What’s a belief you’ve questioned recently?",
    "What does success in relationships look like to you?",
    "What’s the most beautiful thing you’ve ever created?",
    "What is something you’re grateful for today?",
    "What do you think your purpose is in life?",
    "What’s something that brings you comfort when you’re feeling down?",
    "What’s one way you show appreciation to others?",
    "What’s a lesson you learned the hard way?",
    "How do you define balance in life?",
    "What’s the most unexpected lesson you’ve learned recently?",
    "What’s a talent or skill you’re proud of?",
    "What’s one thing that makes you feel at home with yourself?",
    "What’s a piece of advice you would give to someone just starting out in life?",
    "What’s one thing that motivates you every day?",
    "How do you deal with change in your life?",
    "What’s one thing you want to improve about your life?",
    "What’s a moment in your life when you felt completely at peace?",
    "What’s your favorite ritual for starting the day?",
    "What’s something you’ve learned from a setback?",
    "What would your dream day look like?",
    "What’s one thing you would never want to change about yourself?",
    "How do you deal with negative self-talk?",
    "What’s the most memorable compliment you’ve ever received?",
    "What’s something you’ve learned from your family?",
    "What’s something you’re currently trying to let go of?",
    "What’s something you’re learning to accept about yourself?",
    "What’s one thing you wish you could do more often?",
    "What’s one of your happiest memories?",
    "What’s something you’re curious about that you’ve never explored?",
    "What’s a quality you admire in people you look up to?",
    "What’s one thing you want to accomplish before the end of the year?",
    "What’s something that always makes you smile?",
    "What’s a time when you felt out of your comfort zone?",
    "How do you handle uncertainty in your life?",
    "What’s one habit you’ve developed that you’re proud of?",
    "What’s something you feel passionate about right now?",
    "How do you stay motivated when faced with challenges?",
    "What’s something you’ve done that makes you proud?",
    "What’s something you’d like to teach others?",
    "How do you handle self-doubt?",
    "What’s something you do to feel connected to others?",
    "What’s the best decision you’ve made for your health?",
    "What’s something you’ve learned from your failures?",
    "How do you stay true to your values?",
    "What’s something that makes you feel understood?",
    "What does happiness look like for you?",
    "What’s a recent change you’ve made that’s had a positive impact?",
    "What’s one thing you’d like to let go of in your life?",
    "What’s something that helps you recharge your energy?",
    "What’s a new perspective you’ve gained recently?",
    "How do you deal with challenges in your relationships?",
    "What’s one thing you’ve done to improve your mental health?",
    "What’s a quality you admire in yourself?",
    "What’s a habit you’d like to break?",
    "What’s one way you show kindness to others?",
    "What’s the best decision you’ve made for your career?",
    "How do you nurture your creativity?",
    "What’s something you’re working on letting go of?",
    "What’s your definition of fulfillment?",
    "What’s something that makes you feel alive?",
    "What’s one lesson you’ve learned about self-love?",
    "What’s something you’re excited to start doing?",
    "What’s your favorite way to spend a Saturday?",
    "What’s the most important relationship in your life?",
    "What’s something you’ve done that made a positive impact on someone else?",
    "What’s one thing you’d like to create in the future?",
    "How do you feel when you achieve a goal?",
    "What’s one thing that always puts you in a good mood?",
    "What’s something you’re trying to be more mindful of?",
    "What’s the most valuable lesson you’ve learned about happiness?",
    "What’s something you’re proud of overcoming?",
    "How do you stay motivated when life gets tough?",
	"What’s a memory you cherish from childhood?",
    "What’s one way you can help someone today?",
    "What does vulnerability mean to you?",
    "What’s a lesson you’ve learned from a difficult experience?",
    "What’s your favorite way to stay organized?",
    "What’s one thing you want to let go of to feel lighter?",
    "What’s something you’re proud of learning recently?",
    "Write about a time when you had to face a fear.",
    "What’s something that always calms your nerves?",
    "What’s a goal you’ve recently achieved?",
    "How do you stay true to your values in the face of pressure?",
    "What’s one thing you could do to make today better?",
    "What’s something that inspires you to be better every day?",
    "How do you show love to yourself?",
    "What’s one thing you want to accomplish by the end of this year?",
    "What are three qualities you look for in a friend?",
    "What’s something you’ve learned about being patient with yourself?",
    "How do you define inner peace?",
    "What’s something that motivates you when things are tough?",
    "What’s your favorite thing to do on a quiet day?",
    "What’s a quote that always inspires you?",
    "What’s something you would like to do more often for your mental health?",
    "Write about a time when you felt completely understood.",
    "What’s one thing you do to take care of your mental well-being?",
    "What’s your favorite way to express gratitude?",
    "How do you define personal growth?",
    "What’s a habit you’d like to start cultivating?",
    "What’s one thing you want to improve about your daily routine?",
    "What’s the best advice you’ve received about self-care?",
    "What’s your definition of a successful day?",
    "What’s one thing you wish you had more time for?",
    "What’s a personal goal you’re working towards right now?",
    "How do you stay motivated when things aren’t going as planned?",
    "What’s something you’re grateful for today?",
    "Write about a time when you made a positive impact on someone else’s life.",
    "What’s a challenge you’ve recently faced, and how did you handle it?",
    "What’s something you’ve learned from a past mistake?",
    "What’s a tradition you’ve created for yourself?",
    "How do you practice self-compassion?",
    "What’s something that makes you feel accomplished?",
    "What does self-expression mean to you?",
    "What’s one thing you’re excited to learn more about?",
    "What’s your favorite part of the day, and why?",
    "What’s a habit that helps you stay grounded?",
    "What’s something you want to accomplish in the next six months?",
    "What’s a challenge you’re currently facing, and what steps are you taking to overcome it?",
    "What’s a piece of advice you would give to someone feeling lost?",
    "What’s something you’re grateful for that you often overlook?",
    "What’s something you’ve recently realized about yourself?",
    "What’s one quality you admire in people who inspire you?",
    "What does happiness feel like to you?",
    "What’s a time when you felt out of your comfort zone, and how did you grow from it?",
    "How do you measure personal success?",
    "What’s something you’ve always wanted to do but haven’t yet?",
    "How do you cultivate a sense of calm in your life?",
    "What’s something that gives you strength when you feel weak?",
    "What’s one thing you could do today to make tomorrow easier?",
    "What’s something you love about the way you think?",
    "What’s one piece of advice you would give to your younger self?",
    "What’s a moment in your life when you felt proud of yourself?",
    "What’s something you’ve learned from a difficult relationship?",
    "What’s one thing you could do today to improve your health?",
    "What’s something you’re currently trying to understand better?",
    "How do you deal with feeling stuck?",
    "What’s a value that’s important to you, and how do you live by it?",
    "What’s something that always makes you feel confident?",
    "What’s one thing you love about your life right now?",
    "What’s something you’re grateful for about your body?",
    "What’s a memory that always makes you smile?",
    "What’s one thing you could do to reduce stress in your life?",
    "What’s something you’ve learned from your parents or guardians?",
    "What’s something you admire about the way someone you know handles challenges?",
    "What’s your favorite form of creative expression?",
    "What’s one thing you’ve done recently that made you feel proud?",
    "How do you practice mindfulness in your daily life?",
    "What’s one thing you would like to accomplish by the end of the week?",
    "How do you stay motivated when facing difficult tasks?",
    "What’s one thing you’d like to learn about yourself?",
    "What’s the best decision you’ve made for your well-being?",
    "What’s one thing you’re looking forward to this week?",
    "What’s a quality you look for in a mentor?",
    "How do you recharge after a busy week?",
    "What’s something you do to make yourself feel at home wherever you are?",
    "What’s one way you can show appreciation to someone today?",
    "What’s a new habit you’re trying to form?",
    "What’s one thing you’ve learned about building strong relationships?",
    "What’s something that helps you feel connected to others?",
    "What’s one thing you want to change about your mindset?",
    "What’s a decision you’re currently grappling with?",
    "What’s something you love about your current routine?",
    "What’s one thing that always inspires you to keep going?",
    "What’s a lesson you’ve learned about setting boundaries?",
    "What’s something that makes you feel connected to the world around you?",
    "What’s one thing you’d like to accomplish in the next year?",
    "What’s your idea of a perfect day of self-care?",
    "What’s something you’ve learned from a recent experience?",
    "What’s your favorite form of self-expression?",
    "What’s something you’re grateful for about your current stage in life?",
    "What’s one thing that gives you hope for the future?",
    "What’s something that motivates you to keep going even when you’re tired?",
    "What’s one habit you’re proud of cultivating?",
    "What’s a personal value that you hold dear?",
    "What’s one thing you’ve learned about yourself from a recent challenge?",
	"What does a fulfilling life look like to you?",
    "What’s something you’ve done that you once thought was impossible?",
    "How do you define success in your career?",
    "What’s something you’ve learned about yourself through travel?",
    "What’s a difficult decision you had to make recently?",
    "What’s something that helps you stay grounded in chaotic times?",
    "What’s a talent or skill you wish you could develop?",
    "What’s a book that deeply impacted you?",
    "What’s something you wish you had more time to focus on?",
    "What’s one challenge you’re currently working to overcome?",
    "How do you manage your energy during stressful times?",
    "What’s one way you’re taking care of yourself this week?",
    "What’s the most valuable lesson you’ve learned from a mentor?",
    "What’s something you’ve been struggling to let go of?",
    "How do you stay motivated when you’re feeling uninspired?",
    "What’s one thing you love about your personal growth journey?",
    "What’s a time when you felt like you truly understood yourself?",
    "What’s a creative idea you’ve been wanting to explore?",
    "What’s one fear you want to face head-on?",
    "What’s something that brings you joy when you’re feeling down?",
    "What’s a recent realization you’ve had about yourself?",
    "What’s something you’ve learned from a mistake that shaped you?",
    "What’s one thing you want to add to your life to make it more fulfilling?",
    "What’s a new habit you’d like to develop?",
    "What’s one thing you love about the work you do?",
    "What’s a piece of advice you would give to your future self?",
    "What’s a moment in your life when you felt truly present?",
    "What’s one thing you’d like to accomplish in the next month?",
    "How do you find balance in your life?",
    "What’s one thing you’re proud of that you’ve accomplished this year?",
    "What’s something you’ve learned about being patient with others?",
    "What’s one thing that helps you stay focused and productive?",
    "What’s something you’ve recently felt grateful for?",
    "How do you celebrate your successes, big or small?",
    "What’s one quality you admire in others and would like to cultivate in yourself?",
    "What’s something you wish you could change about your routine?",
    "What’s one lesson you’ve learned about resilience?",
    "What’s a practice that helps you stay positive in tough situations?",
    "What’s one thing you want to let go of in your life?",
    "What’s a place that brings you peace, and why?",
    "What’s something you’ve been learning lately that excites you?",
    "What’s something you’ve always wanted to do but never had the chance?",
    "What’s one of your favorite ways to relax and recharge?",
    "What’s a recent experience that taught you something new about yourself?",
    "What’s something you’ve been meaning to do but haven’t gotten around to?",
    "What’s a piece of advice you’d give to someone just starting out in life?",
    "What’s something you’ve learned from someone you look up to?",
    "What’s one decision you’re glad you made in the past?",
    "What’s a time when you felt truly connected to someone?",
    "What’s one thing you love about your personality?",
    "What’s something you’ve learned about vulnerability?",
    "What’s one way you show gratitude to others?",
    "What’s something you do to stay mentally sharp?",
    "What’s one thing you’ve been struggling with lately?",
    "What’s something that makes you feel at peace?",
    "What’s a goal you have for the next year, and how will you achieve it?",
    "What’s something you’re grateful for about your upbringing?",
    "What’s a piece of advice that has stuck with you over the years?",
    "What’s one thing you do to celebrate the little victories in life?",
    "What’s something that makes you feel confident?",
    "What’s a skill you want to improve, and why?",
    "What’s one way you practice self-compassion?",
    "What’s something you’ve learned from observing others?",
    "What’s a belief you hold that’s shaped your life in a positive way?",
    "What’s one thing you’re currently doing to better your future?",
    "What’s something you want to do more of in your daily life?",
    "What’s a lesson you’ve learned about being present?",
    "What’s one thing you wish others knew about you?",
    "What’s a decision you made that changed the course of your life?",
    "What’s one way you help others feel heard and understood?",
    "What’s something that excites you about your future?",
    "What’s something you’ve done that made a positive impact on someone’s life?",
    "What’s something you’ve learned from a past relationship?",
    "What’s one way you’ve been practicing mindfulness lately?",
    "What’s a time you overcame a challenge you thought was insurmountable?",
    "What’s one thing you’ve learned from your failures?",
    "What’s something you’re grateful for about your body?",
    "What’s one thing you want to do differently this week?",
    "What’s a piece of advice you would give to your younger self?",
    "What’s one thing you love about the way you approach life?",
    "What’s a time when you felt truly understood by someone?",
    "What’s one thing that always lifts your spirits?",
    "What’s something that’s currently bringing you peace?",
    "What’s one thing you want to achieve by the end of this year?",
    "What’s something that inspires you every day?",
    "What’s a belief you’ve changed your mind about?",
    "What’s one way you challenge yourself to grow?",
    "What’s something you’d like to try, but haven’t had the courage to yet?",
    "What’s a habit you’d like to break, and why?",
    "What’s something you’ve learned recently that made you rethink something?",
    "What’s a new skill you’d like to develop?",
    "What’s one thing that makes you feel truly alive?",
    "What’s something that helps you focus when you feel distracted?",
    "What’s one thing you’re doing to strengthen your relationships?",
    "What’s one thing you wish you could change about your routine?",
    "What’s a moment you felt proud of yourself for handling a difficult situation?",
    "What’s one thing that always makes you laugh?",
    "What’s something you’ve learned from a mentor or role model?",
    "What’s one thing you do to feel more present in the moment?",
    "What’s one thing you’re grateful for today?",
	"What’s one thing you’ve been avoiding, and why?",
    "How do you define freedom in your life?",
    "What’s a childhood dream you’ve never given up on?",
    "What’s something you’ve done recently that made you proud of yourself?",
    "What’s one thing you can do today to improve your tomorrow?",
    "What’s a recent change you’ve made that has had a positive impact on your life?",
    "What’s something you can do to show appreciation for the people around you?",
    "What’s one thing you love about your morning routine?",
    "What’s something you’ve learned about yourself from a tough situation?",
    "What’s one way you express your creativity in everyday life?",
    "What’s one thing you’re excited to work on in the next month?",
    "What’s a small act of kindness you’ve received that stuck with you?",
    "What’s something that challenges your sense of comfort?",
    "What’s a book that opened your mind in a new way?",
    "What’s something you’ve learned about love in the last year?",
    "What’s a skill or talent you wish to develop in the next year?",
    "What’s something that always makes you feel safe?",
    "How do you define happiness in your own life?",
    "What’s something you’ve recently done to step outside your comfort zone?",
    "What’s a habit that’s been positively impacting your well-being?",
    "What’s a goal you’re working toward that excites you?",
    "What’s something you’re grateful for that’s often overlooked?",
    "What’s one challenge you overcame that made you stronger?",
    "What’s one thing you’ve learned from a mentor or role model?",
    "What’s something you’ve always wanted to create but haven’t yet?",
    "What’s one of the most valuable things you’ve learned about yourself?",
    "What’s something you can do today to make your future self proud?",
    "What’s a recent memory that made you feel completely at peace?",
    "What’s something you want to start doing regularly for your health?",
    "What’s one habit you’ve tried to break, and how did you approach it?",
    "What’s something you’ve learned about forgiveness?",
    "What’s one thing you can do to increase your daily productivity?",
    "What’s one piece of advice you’d give to someone feeling lost?",
    "What’s a time when you had to trust the process and let go of control?",
    "What’s something that helps you reconnect with yourself?",
    "What’s something that challenges your mindset in a good way?",
    "What’s something you do to help others feel heard and supported?",
    "What’s a memory you cherish with a loved one?",
    "What’s something that made you smile today?",
    "What’s a recent achievement you’re proud of?",
    "What’s one thing that makes you feel more connected to others?",
    "What’s something you’ve learned from a past experience that you still carry with you?",
    "What’s something you’re currently working on that excites you?",
    "What’s a recent discovery about yourself that you’re excited about?",
    "What’s something that helps you calm down when you’re anxious?",
    "What’s one piece of advice you would give to your future self?",
    "What’s a moment in your life when you truly felt alive?",
    "What’s one thing you’d like to achieve by the end of this month?",
    "What’s something you’ve recently let go of that you were holding on to?",
    "What’s something you’d like to do more often for your mental well-being?",
    "What’s a habit that you believe will lead to long-term success?",
    "What’s something that brings you joy when you’re feeling overwhelmed?",
    "What’s something you admire about your own resilience?",
    "What’s one thing you’ve learned about healthy boundaries?",
    "What’s a time when you learned something new that shifted your perspective?",
    "What’s a goal you’ve set for yourself, and how are you working toward it?",
    "What’s a value you hold dear, and how does it shape your decisions?",
    "What’s something you’ve learned about taking risks?",
    "What’s one thing you can do today to make your day more fulfilling?",
    "What’s something you’ve recently done to celebrate yourself?",
    "What’s a time when you felt truly appreciated by someone?",
    "What’s a piece of advice you would give to your younger self about love?",
    "What’s something you’ve learned about forgiveness and healing?",
    "What’s a habit you’re trying to build to improve your life?",
    "What’s something you’ve learned about letting go of control?",
    "What’s a way you’ve been practicing gratitude lately?",
    "What’s one thing you’ve learned from a difficult situation that has shaped you?",
    "What’s something you’ve done recently that made you feel empowered?",
    "What’s something you’re passionate about but haven’t made time for?",
    "What’s one thing you’d like to change about your mindset?",
    "What’s a time when you stepped outside your comfort zone and grew from it?",
    "What’s something that always brings you peace of mind?",
    "What’s one thing you can do today to improve your self-awareness?",
    "What’s something that brings you a sense of accomplishment?",
    "What’s a lesson you’ve learned from a past challenge that’s still relevant today?",
    "What’s something you’ve recently discovered about the way you work best?",
    "What’s one thing you’d like to do for your emotional well-being today?",
    "What’s something you love about your routine?",
    "What’s a skill you want to improve that will help you in the long run?",
    "What’s something you’ve learned from your experiences with failure?",
    "What’s one thing you want to do more often to feel balanced?",
    "What’s a piece of advice you’ve found helpful in times of stress?",
    "What’s a recent accomplishment that made you feel proud?",
    "What’s one way you practice self-compassion when things don’t go as planned?",
    "What’s something you’ve learned about the importance of patience?",
    "What’s a goal you’ve been working toward that you’re excited to achieve?",
    "What’s something you’ve recently let go of to make space for growth?",
    "What’s one thing you’re grateful for about today?",
    "What’s something that makes you feel truly appreciated?",
    "What’s a time you took a risk that paid off?",
    "What’s something you wish you could do more of in your daily life?",
    "What’s one piece of advice you’ve heard that you want to live by?",
    "What’s something you’ve recently discovered about how you think?",
    "What’s one habit you’d like to start incorporating into your life?",
    "What’s something you’ve learned about perseverance?",
    "What’s a lesson you’ve learned about being open to change?",
    "What’s something you’re grateful for that you often overlook?",
	"What’s something you’ve recently done that challenged your limits?",
    "What’s a place you’ve always wanted to visit, and why?",
    "What’s something you’ve learned about setting healthy boundaries?",
    "What’s one thing you would like to change about your perspective?",
    "What’s a memory that always makes you smile?",
    "What’s one thing you do to stay calm in difficult situations?",
    "What’s something you’ve learned about the power of vulnerability?",
    "What’s a time when you were amazed by someone’s kindness?",
    "What’s one skill you would love to master in the next year?",
    "What’s something you’ve done recently that made you feel alive?",
    "What’s one thing you can do to nurture your creativity today?",
    "What’s something that helps you stay focused on your goals?",
    "What’s one way you can improve your self-care routine?",
    "What’s something you’d like to improve about your daily habits?",
    "What’s a decision you made that you’re really proud of?",
    "What’s a habit you’ve been trying to develop to improve your life?",
    "What’s one thing that inspires you to keep going on tough days?",
    "What’s something you’ve learned about yourself through a challenge?",
    "What’s one belief you have about life that has shaped your journey?",
    "What’s something you love about your current routine?",
    "What’s a place that always makes you feel at peace?",
    "What’s something you’re working on to improve your health?",
    "What’s one thing you’ve learned about resilience?",
    "What’s something that brings you joy every day?",
    "What’s one way you practice gratitude in your daily life?",
    "What’s something you’ve been holding on to that you need to let go of?",
    "What’s a goal you’ve set for yourself that you’re excited about?",
    "What’s one thing you’ve learned about embracing imperfection?",
    "What’s something you do to stay motivated when you’re feeling low?",
    "What’s something you’re proud of that you don’t share with others often?",
    "What’s one piece of advice you would give to someone starting fresh?",
    "What’s something you’re grateful for about your work or career?",
    "What’s a quality you admire in others that you’d like to cultivate?",
    "What’s something you’ve learned about patience in your life?",
    "What’s one thing you love about your personality?",
    "What’s something you’ve recently learned that made you rethink something?",
    "What’s a small change you can make today to improve your day?",
    "What’s one thing you’ve always wanted to try but haven’t yet?",
    "What’s something that has changed your perspective on life recently?",
    "What’s one thing you do when you’re feeling disconnected from yourself?",
    "What’s something you’d like to accomplish before the end of the year?",
    "What’s a challenge you’ve faced that taught you valuable lessons?",
    "What’s one thing you’re currently working on to improve your mindset?",
    "What’s something you’ve learned from someone who’s different from you?",
    "What’s one thing you can do today to brighten someone else’s day?",
    "What’s something you’ve done that made you feel truly confident?",
    "What’s a value you hold dear that influences your decisions?",
    "What’s one thing that helps you remain optimistic in uncertain times?",
    "What’s a decision you made that you’ve never regretted?",
    "What’s one thing you’d like to change about your relationship with time?",
    "What’s something you’ve learned about taking responsibility for your actions?",
    "What’s one thing you would like to create in the next six months?",
    "What’s something you’ve learned from failure that you’re thankful for?",
    "What’s one quality you’d like to develop more of in yourself?",
    "What’s something that motivates you to take action toward your goals?",
    "What’s one thing you’re doing today to move closer to your dreams?",
    "What’s a time when you felt deeply understood by someone?",
    "What’s something you’ve recently learned about being present?",
    "What’s one thing you’ve learned about setting and achieving goals?",
    "What’s something you’ve done that made you proud of your growth?",
    "What’s a piece of advice you wish everyone knew about self-care?",
    "What’s one thing you would like to accomplish this month?",
    "What’s something you’ve done recently that was outside of your comfort zone?",
    "What’s one thing you’ve learned about maintaining balance in life?",
    "What’s something you’d like to try that could help you grow as a person?",
    "What’s a habit you’ve developed that has positively impacted your life?",
    "What’s one thing you’ve learned about self-compassion?",
    "What’s something you’ve recently realized about the importance of rest?",
    "What’s one challenge you’re currently facing and how you’re handling it?",
    "What’s something you’ve learned about the importance of boundaries?",
    "What’s something that always makes you feel grounded?",
    "What’s one thing you’d like to change about your routine to make it better?",
    "What’s something you’ve recently done to strengthen your mental health?",
    "What’s one thing you love about the way you approach problems?",
    "What’s something you’ve learned about focusing on the present moment?",
    "What’s something you’re grateful for that you usually take for granted?",
    "What’s a recent memory that reminded you of your resilience?",
    "What’s one thing you’d like to accomplish by the end of this week?",
    "What’s something you’ve done that you once thought was impossible?",
    "What’s one way you express your creativity that you enjoy the most?",
    "What’s something you’ve learned about the power of vulnerability?",
    "What’s one thing you’ve done recently that made you feel at peace?",
    "What’s a practice that helps you stay connected to your inner self?",
    "What’s something you’ve learned from others that has shifted your mindset?",
    "What’s one thing you can do today to help you feel more accomplished?",
    "What’s something you’ve learned from a mentor that changed your life?",
    "What’s one thing you’d like to explore in your creative life?",
    "What’s something you’re proud of that you’ve worked hard to achieve?",
    "What’s one thing that helps you stay motivated even when it’s hard?",
    "What’s a recent experience that made you rethink something in your life?",
    "What’s something you can do to foster more connection in your relationships?",
    "What’s one thing you’re doing to keep moving forward despite setbacks?",
    "What’s something you’ve learned from a challenge you’re still grateful for?",
	    "What’s something you’ve done recently that made you feel proud?",
    "What’s one of your favorite memories from childhood, and why does it stand out?",
    "What’s something you wish you could let go of, but you still hold on to?",
    "What’s one thing you’ve learned about trust in your life?",
    "What’s something you’re working on to improve your physical health?",
    "What’s one small change you can make today that would improve your tomorrow?",
    "What’s something you’ve recently done that you never thought you would?",
    "What’s a book, article, or podcast that you’ve recently found inspiring?",
    "What’s something you’ve learned about your emotional needs?",
    "What’s a personal goal you want to achieve in the next three months?",
    "What’s a time when you felt truly seen by someone?",
    "What’s one thing you do every day that helps you feel centered?",
    "What’s something you’ve done to push yourself outside of your comfort zone?",
    "What’s something you love about the way you think?",
    "What’s something you’ve learned about patience and how it can improve your life?",
    "What’s one thing you’re grateful for about your current life situation?",
    "What’s something you’ve learned about maintaining healthy relationships?",
    "What’s something you would like to learn more about in the next year?",
    "What’s one thing you can do to be kinder to yourself?",
    "What’s something that always brings you peace when life gets overwhelming?",
    "What’s something you’ve realized about the importance of rest?",
    "What’s a time when you felt completely in the moment?",
    "What’s something you’ve been putting off but feel ready to tackle now?",
    "What’s something you’re proud of that took time and effort to achieve?",
    "What’s a skill you’re currently developing, and how are you improving it?",
    "What’s one habit you’ve adopted that has had a positive impact on your life?",
    "What’s something you’ve learned from a mentor or role model?",
    "What’s something you’re currently doing to improve your mental health?",
    "What’s one thing you’ve learned from a difficult conversation?",
    "What’s something you’re excited about accomplishing in the next month?",
    "What’s a recent moment that made you feel deeply connected to others?",
    "What’s something you’ve done that made you feel empowered?",
    "What’s one thing you’ve recently learned about setting boundaries?",
    "What’s something you’ve been curious about but haven’t explored yet?",
    "What’s one way you’ve grown emotionally in the last year?",
    "What’s a habit you’d like to break and what are the first steps you can take?",
    "What’s something you can do today to nurture your creativity?",
    "What’s something you’ve learned about vulnerability in relationships?",
    "What’s something you can do to improve your daily routine?",
    "What’s one thing you’ve learned about the importance of self-compassion?",
    "What’s something you’ve done that made you feel completely in control?",
    "What’s one way you practice mindfulness in your everyday life?",
    "What’s something you’ve learned about forgiving others and yourself?",
    "What’s one challenge you’ve overcome that you didn’t expect to?",
    "What’s a time when you took a big risk and it paid off?",
    "What’s something you’ve recently learned that changed your perspective?",
    "What’s something you want to start doing more often for your well-being?",
    "What’s a lesson you’ve learned from a past relationship that shaped you?",
    "What’s something you’ve done recently that made you feel connected to nature?",
    "What’s something you’re looking forward to in the next year?",
    "What’s one thing you can do to strengthen your emotional resilience?",
    "What’s a value you hold dear, and how do you practice it in your life?",
    "What’s something you’ve learned about the importance of laughter?",
    "What’s a recent experience that made you feel proud of yourself?",
    "What’s something you’ve been learning about yourself recently?",
    "What’s one thing you would tell your future self about love and relationships?",
    "What’s something you’ve done recently to prioritize your happiness?",
    "What’s something you’re passionate about that you want to share with others?",
    "What’s one thing you can do today to strengthen your self-discipline?",
    "What’s something you’ve learned from a past failure that helped you succeed?",
    "What’s something you’ve been procrastinating on that you’re now ready to tackle?",
    "What’s one thing you’ve learned about the importance of slowing down?",
    "What’s a time when you felt completely supported by someone?",
    "What’s something you’ve done recently that made you feel brave?",
    "What’s a habit you’ve cultivated that has made your life easier?",
    "What’s one thing you can do today to practice gratitude?",
    "What’s something you’ve learned about letting go of expectations?",
    "What’s something you’re grateful for that you once took for granted?",
    "What’s one way you’ve learned to manage your time more effectively?",
    "What’s something you’re excited to accomplish this month?",
    "What’s a practice that helps you feel more connected to your inner peace?",
    "What’s one way you’re stepping outside your comfort zone right now?",
    "What’s something you’ve learned about the power of positive self-talk?",
    "What’s one thing you’ve learned about resilience through a difficult experience?",
    "What’s something that you find challenging but you enjoy doing anyway?",
    "What’s one thing you can do today to improve your mental clarity?",
    "What’s something you’ve learned about the importance of self-reflection?",
    "What’s a time when you found strength in a difficult situation?",
    "What’s one thing you can do today to create a more fulfilling life?",
    "What’s something you’ve done recently that made you feel confident?",
    "What’s one thing you’ve learned about setting goals that works for you?",
    "What’s something you’ve recently done to embrace your authenticity?",
    "What’s a lesson you’ve learned about patience and timing?",
    "What’s one thing you’d like to do today to take care of yourself?",
    "What’s something you’ve learned about healthy communication in relationships?",
    "What’s something you’d like to accomplish by the end of this week?",
    "What’s a recent achievement that made you feel accomplished?",
    "What’s one thing you can do today to make progress toward your dreams?",
    "What’s something you’ve learned about the importance of taking breaks?",
    "What’s one thing you can do to foster a sense of calm in your life?",
    "What’s something you’ve done recently that challenged your perspective?",
	"What’s one thing you’ve learned recently that changed the way you see the world?",
    "What’s something you do to stay motivated when things get tough?",
    "What’s one thing you would do if you knew you couldn’t fail?",
    "What’s something that’s been on your mind lately that you need to explore?",
    "What’s one way you can bring more joy into your daily life?",
    "What’s something that makes you feel grateful for the present moment?",
    "What’s one thing you can do today to be kinder to others?",
    "What’s a memory that always brings you comfort when you need it most?",
    "What’s something that’s been holding you back from reaching your goals?",
    "What’s one piece of advice you would give your younger self?",
    "What’s something you’re passionate about that you’d like to pursue more?",
    "What’s a habit you’re trying to break, and what steps are you taking to do it?",
    "What’s one thing you’d like to accomplish by the end of this year?",
    "What’s something that helps you stay grounded when life feels chaotic?",
    "What’s one thing you’ve learned about the importance of taking risks?",
    "What’s something that’s currently inspiring you in your personal life?",
    "What’s one way you practice self-care that makes a big difference?",
    "What’s something you’ve learned about building trust with others?",
    "What’s one goal you’ve set for yourself this month, and why is it important?",
    "What’s something you’ve done recently that made you feel proud of yourself?",
    "What’s one thing you can do today to challenge yourself and grow?",
    "What’s a lesson you’ve learned from a difficult decision you’ve had to make?",
    "What’s one thing you’ve learned about embracing change in your life?",
    "What’s something you’ve recently discovered about your own strengths?",
    "What’s a goal you’ve set that excites you, but also scares you a little?",
    "What’s something you’ve been meaning to try but haven’t yet?",
    "What’s one way you practice mindfulness in your daily routine?",
    "What’s something you’ve done recently to help someone else?",
    "What’s one thing you love about the way you approach challenges?",
    "What’s something that has changed the way you think about happiness?",
    "What’s one thing you can do today to make someone’s day better?",
    "What’s something you’re currently working on to improve your emotional health?",
    "What’s one way you can support others in your community this week?",
    "What’s something you’ve learned about perseverance in your life?",
    "What’s one thing you wish you could spend more time doing?",
    "What’s a challenge you’ve faced recently that helped you grow?",
    "What’s something you’d like to teach others about self-compassion?",
    "What’s one way you stay connected to your passions, even on tough days?",
    "What’s something that helps you feel connected to your purpose?",
    "What’s one thing you can do today to express gratitude?",
    "What’s something you’ve learned about the importance of rest and recovery?",
    "What’s one lesson you’ve learned about letting go of perfectionism?",
    "What’s something you’ve done that helped you overcome a fear?",
    "What’s one thing you’d like to create in the next year?",
    "What’s something you’ve recently done that made you feel empowered?",
    "What’s one thing you can do today to make progress toward your long-term goals?",
    "What’s something you’ve learned from someone who’s different from you?",
    "What’s one thing you can do today to create a more fulfilling routine?",
    "What’s something you’ve been struggling with, and how can you overcome it?",
    "What’s one small act of kindness you can do today for someone else?",
    "What’s something you’ve done recently that made you feel confident?",
    "What’s one thing you’d like to change about your mindset?",
    "What’s something you’ve recently learned about self-discipline?",
    "What’s one way you can practice gratitude for your body today?",
    "What’s something you’ve done recently that made you feel connected to others?",
    "What’s one thing you can do today to boost your self-esteem?",
    "What’s something you’ve learned about the power of positive thinking?",
    "What’s one habit you’d like to develop to improve your emotional well-being?",
    "What’s something you can do today to make your environment more peaceful?",
    "What’s one thing you’ve done recently that made you feel at peace?",
    "What’s one thing you can do to nurture your relationships with others?",
    "What’s something you’ve learned about the importance of being present?",
    "What’s one thing you’d like to create in the next few months?",
    "What’s something you’ve recently learned about managing your energy?",
    "What’s one thing you can do to bring more creativity into your life?",
    "What’s something you’ve done that made you feel truly authentic?",
    "What’s one thing you can do today to work toward your dreams?",
    "What’s something you’ve done recently that made you feel proud of your growth?",
    "What’s one thing you can do to practice more patience with yourself?",
    "What’s something you’ve learned about the importance of setting boundaries?",
    "What’s something that always makes you feel relaxed and calm?",
    "What’s one thing you can do today to improve your mental clarity?",
    "What’s something you’ve learned about the importance of balance in your life?",
    "What’s one thing you’ve done that made you feel empowered in a situation?",
    "What’s something you’ve learned about dealing with setbacks in life?",
    "What’s one thing you can do today to take better care of your physical health?",
    "What’s something you’ve learned about the value of taking time for yourself?",
    "What’s one thing you can do today to feel more accomplished?",
    "What’s something you’ve recently done that made you feel connected to your purpose?",
    "What’s one thing you can do to make today a fulfilling day?",
    "What’s something you’ve learned about the importance of nurturing your passions?",
    "What’s one thing you can do today to strengthen your mental resilience?",
    "What’s something you’ve done that made you feel completely at ease?",
    "What’s one thing you’ve learned about the importance of self-awareness?",
	"What’s something that makes you feel grounded when life gets overwhelming?",
    "What’s one thing you can do today to strengthen your personal boundaries?",
    "What’s something you’ve learned about managing stress in your life?",
    "What’s one way you can practice self-love today?",
    "What’s something that has helped you cultivate resilience in difficult times?",
    "What’s a time when you felt like you were exactly where you needed to be?",
    "What’s one thing you’ve learned about the power of positive reinforcement?",
    "What’s a recent experience that made you feel truly grateful?",
    "What’s one area of your life where you’d like to show more compassion?",
    "What’s one thing you can do today to be more present in the moment?",
    "What’s something you’ve recently done that helped you regain your confidence?",
    "What’s one practice you’ve adopted that helps you feel balanced?",
    "What’s one way you express gratitude towards yourself?",
    "What’s a goal you’ve set for yourself this month, and why is it meaningful?",
    "What’s something you’ve learned about slowing down and enjoying life?",
    "What’s one thing you can do today to make time for yourself?",
    "What’s a lesson you’ve learned from a challenging experience that shaped you?",
    "What’s something you’ve done recently to connect with others in a meaningful way?",
    "What’s one thing you can do today to embrace change in your life?",
    "What’s something you’ve learned about the importance of being open to new opportunities?",
    "What’s something that has helped you let go of fears or insecurities?",
    "What’s one thing you can do today to create a sense of peace in your environment?",
    "What’s something you’ve learned about the impact of your thoughts on your reality?",
    "What’s a time when you felt deeply connected to your intuition?",
    "What’s one thing you can do today to improve your self-esteem?",
    "What’s something you’ve recently done that made you feel empowered?",
    "What’s one thing you’ve learned about the importance of mindful communication?",
    "What’s something you’re grateful for that you never thought you’d appreciate?",
    "What’s one way you can practice acceptance in your life today?",
    "What’s something you’ve learned about the power of letting go?",
    "What’s one thing you can do today to connect more deeply with your purpose?",
    "What’s something you’ve done recently that made you feel proud of your growth?",
    "What’s one habit you’re working on cultivating that’s making a positive difference in your life?",
    "What’s something you’ve learned about balancing ambition and self-compassion?",
    "What’s one thing you can do today to make a positive impact on someone else’s life?",
    "What’s something you’ve done recently that challenged your fears?",
    "What’s one thing you can do to honor your emotional needs today?",
    "What’s something you’ve learned about forgiveness and how it has helped you heal?",
    "What’s one way you can improve your ability to handle difficult emotions?",
    "What’s something you’ve done recently that made you feel fully alive?",
    "What’s one thing you can do today to deepen your self-awareness?",
    "What’s something you’ve learned about how your values influence your decisions?",
    "What’s one practice you’ve adopted that helps you stay focused and calm?",
    "What’s something you’ve learned about the importance of asking for help?",
    "What’s one thing you can do today to prioritize your mental well-being?",
    "What’s something you’ve done recently that made you feel connected to your creativity?",
    "What’s one thing you’ve learned about maintaining healthy boundaries in relationships?",
    "What’s something you can do today to practice gratitude for your body?",
    "What’s something you’ve learned about the importance of time management?",
    "What’s one way you can express your emotions more openly?",
    "What’s something you’ve recently learned about finding balance in your life?",
    "What’s one thing you can do today to strengthen your connection to nature?",
    "What’s something you’ve done that helped you build self-confidence?",
    "What’s one thing you can do today to create a positive impact on your future?",
    "What’s something you’ve learned about managing your time effectively?",
    "What’s one thing you’ve done recently that made you feel proud of your accomplishments?",
    "What’s something you can do today to practice mindfulness?",
    "What’s something you’ve learned about dealing with uncertainty in your life?",
    "What’s one way you can practice being more patient with yourself today?",
    "What’s something you’ve done recently that made you feel more grounded?",
    "What’s one thing you can do today to increase your sense of joy?",
    "What’s something you’ve learned about embracing vulnerability in relationships?",
    "What’s one thing you can do today to take care of your mental health?",
    "What’s something you’ve learned about creating healthy routines that serve your goals?",
    "What’s one thing you can do today to improve your physical health?",
    "What’s something you’ve done recently that made you feel accomplished?",
    "What’s one way you can cultivate more positivity in your daily life?",
    "What’s something you’ve learned about letting go of perfectionism?",
    "What’s one thing you can do today to celebrate your uniqueness?",
    "What’s something you’ve recently learned about your strengths and how they empower you?",
    "What’s one thing you can do today to deepen your sense of self-love?",
    "What’s something you’ve learned about the importance of consistency in your life?",
    "What’s one practice you’ve adopted that helps you stay positive?",
    "What’s something you’ve done recently that made you feel truly confident?",
    "What’s one thing you can do today to make progress on a long-term project?",
    "What’s something you’ve learned about trusting your instincts?",
    "What’s one thing you can do today to create a more supportive environment for yourself?",
    "What’s something you’ve done that made you feel fully present in the moment?",
    "What’s one thing you can do today to cultivate a sense of gratitude?",
    "What’s something you’ve learned about the impact of self-talk on your emotions?",
    "What’s one way you can incorporate more fun and playfulness into your day?",
    "What’s something you’ve done recently that made you feel connected to your values?",
    "What’s one thing you can do today to express your creativity more freely?",
    "What’s something you’ve learned about the importance of creating space for yourself?",
    "What’s one thing you can do today to nurture your spiritual well-being?",
	    "What’s something you’ve learned about the importance of emotional honesty?",
    "What’s one way you can improve your relationship with time?",
    "What’s something that you feel passionate about but haven’t pursued yet?",
    "What’s a simple thing you can do today to nurture your creativity?",
    "What’s something you’ve learned about the connection between your thoughts and emotions?",
    "What’s one thing you can do today to practice being kind to yourself?",
    "What’s something that makes you feel empowered when facing challenges?",
    "What’s one area of your life where you’d like to cultivate more patience?",
    "What’s something you’ve done recently that made you feel truly aligned with your values?",
    "What’s one thing you’ve learned about the power of gratitude?",
    "What’s something you can do today to celebrate your small wins?",
    "What’s one way you’ve recently overcome self-doubt?",
    "What’s something you’ve learned about the power of saying no?",
    "What’s one habit you’d like to develop to improve your overall well-being?",
    "What’s something you’ve done recently that made you feel more connected to your inner self?",
    "What’s one way you can practice mindfulness during your daily routine?",
    "What’s something you’ve learned about the importance of balancing work and rest?",
    "What’s one thing you can do today to break out of your comfort zone?",
    "What’s something you’ve learned about maintaining mental clarity in chaotic times?",
    "What’s one area of your life where you’d like to show more resilience?",
    "What’s something you’ve recently discovered about your emotional triggers?",
    "What’s one thing you can do today to improve your emotional intelligence?",
    "What’s something you’ve learned about dealing with disappointment?",
    "What’s one way you can celebrate your progress on your personal goals?",
    "What’s something you’ve learned about the importance of self-reflection?",
    "What’s one thing you can do today to embrace new opportunities?",
    "What’s something you’ve learned about staying grounded in moments of uncertainty?",
    "What’s one way you can simplify your life to focus on what truly matters?",
    "What’s something you’ve done recently that made you feel proud of your growth?",
    "What’s one thing you can do today to cultivate more peace in your mind?",
    "What’s something you’ve learned about the power of letting go of what no longer serves you?",
    "What’s one thing you can do today to strengthen your relationships?",
    "What’s something you’ve done recently that helped you break a bad habit?",
    "What’s one thing you can do today to enhance your connection with others?",
    "What’s something you’ve learned about the importance of nurturing your passions?",
    "What’s one way you can practice forgiveness today?",
    "What’s something you’ve done recently that made you feel deeply fulfilled?",
    "What’s one thing you can do today to expand your comfort zone?",
    "What’s something you’ve learned about the importance of self-discipline?",
    "What’s one thing you can do today to make progress toward your dreams?",
    "What’s something you’ve learned about finding peace in the present moment?",
    "What’s one thing you can do today to give yourself permission to rest?",
    "What’s something you’ve learned about embracing the unknown?",
    "What’s one thing you can do today to deepen your connection to your creative side?",
    "What’s something you’ve done recently that made you feel proud of your resilience?",
    "What’s one thing you can do today to practice patience with yourself?",
    "What’s something you’ve learned about the power of embracing change?",
    "What’s one thing you can do today to improve your sense of purpose?",
    "What’s something you’ve done recently that made you feel more connected to nature?",
    "What’s one way you can cultivate more joy in your life today?",
    "What’s something you’ve learned about how your thoughts shape your experiences?",
    "What’s one thing you can do today to strengthen your sense of self-worth?",
    "What’s something you’ve recently done that made you feel truly alive?",
    "What’s one thing you can do today to nurture your emotional health?",
    "What’s something you’ve learned about the importance of maintaining boundaries?",
    "What’s one thing you can do today to connect more deeply with your purpose?",
    "What’s something you’ve done recently that made you feel more centered?",
    "What’s one thing you can do today to release any negative energy you’re holding onto?",
    "What’s something you’ve learned about the importance of focusing on the present moment?",
    "What’s one thing you can do today to embrace your vulnerability?",
    "What’s something you’ve done recently that made you feel confident in yourself?",
    "What’s one thing you can do today to create more clarity in your life?",
    "What’s something you’ve learned about the importance of self-compassion?",
    "What’s one thing you can do today to practice gratitude for the little things?",
    "What’s something you’ve done recently that helped you feel more aligned with your goals?",
    "What’s one thing you can do today to express yourself more authentically?",
    "What’s something you’ve learned about the importance of mindfulness in daily life?",
    "What’s one thing you can do today to focus on your mental well-being?",
    "What’s something you’ve learned about the importance of living intentionally?",
    "What’s one thing you can do today to celebrate your uniqueness?",
    "What’s something you’ve done recently that made you feel connected to your values?",
    "What’s one thing you can do today to bring more balance to your life?",
    "What’s something you’ve learned about finding peace during difficult times?",
    "What’s one thing you can do today to focus on your personal growth?",
    "What’s something you’ve learned about the importance of self-awareness?",
    "What’s one thing you can do today to foster more gratitude in your life?",
    "What’s something you’ve done recently that made you feel truly content?",
    "What’s one thing you can do today to appreciate the present moment more fully?",
    "What’s something you’ve learned about the power of listening to your inner voice?",
    "What’s one thing you can do today to make your environment feel more peaceful?",
    "What’s something you’ve done recently that made you feel empowered?",
    "What’s one thing you can do today to improve your relationship with time?",
    "What’s something you’ve learned about the importance of setting boundaries with others?",
    "What’s one thing you can do today to bring more joy into your routine?",
    "What’s something you’ve done recently that made you feel more confident in your decisions?",
    "What’s one thing you can do today to take a step toward your dreams?"
  ];

  const [selectedTab, setSelectedTab] = useState("prompt");
  const [currentPrompt, setCurrentPrompt] = useState(prompts[0]);
  const [entry, setEntry] = useState("");
  const [entries, setEntries] = useState([]);
  const [editingIndex, setEditingIndex] = useState(null);
  const [tags, setTags] = useState("");
  const [search, setSearch] = useState("");
  const [darkMode, setDarkMode] = useState(false);
// 1. Load Dark Mode preference from localStorage on component mount
  useEffect(() => {
    const savedMode = localStorage.getItem("dark-mode");
    if (savedMode === "true") {
      setDarkMode(true);
    }
  }, []);

  // 2. Apply dark mode to the document body whenever darkMode state changes
  useEffect(() => {
    document.body.className = darkMode ? "dark" : "";
    localStorage.setItem("dark-mode", darkMode);  // Save to localStorage
  }, [darkMode]);

  // Load saved journal entries from localStorage
  useEffect(() => {
    const savedEntries = localStorage.getItem("journal-entries");
    if (savedEntries) {
      setEntries(JSON.parse(savedEntries));
    }
  }, []);

  // Save journal entries to localStorage whenever they change
  useEffect(() => {
    if (entries.length > 0) {
      localStorage.setItem("journal-entries", JSON.stringify(entries));
    }
  }, [entries]);

  // Handle saving or updating an entry
  const handleSave = () => {
    if (!entry.trim()) return;
    const newEntry = {
      prompt: currentPrompt,
      text: entry,
      tags: tags.split(",").map(tag => tag.trim()).filter(Boolean),
      date: new Date().toLocaleString(),
    };

    const updatedEntries = [...entries];
    if (editingIndex !== null) {
      updatedEntries[editingIndex] = newEntry;
      setEditingIndex(null);
    } else {
      updatedEntries.unshift(newEntry);
    }

    setEntries(updatedEntries);
    setEntry("");
    setTags("");
  };

  // Handle editing an existing entry
  const handleEdit = (index) => {
    const selected = entries[index];
    setEntry(selected.text);
    setCurrentPrompt(selected.prompt);
    setTags(selected.tags.join(", "));
    setEditingIndex(index);
    setSelectedTab("prompt");
  };

  // Handle deleting an entry
  const handleDelete = (index) => {
    const updated = [...entries];
    updated.splice(index, 1);
    setEntries(updated);
  };

  // Handle downloading an entry as a PDF
  const handleDownload = (entry) => {
    const doc = new jsPDF();
    doc.setFontSize(12);
    doc.text(`Prompt: ${entry.prompt}`, 10, 20);
    doc.text(`Tags: ${entry.tags.join(", ")}`, 10, 30);
    doc.text(`Date: ${entry.date}`, 10, 40);
    doc.text("Entry:", 10, 50);
    doc.text(entry.text, 10, 60, { maxWidth: 180 });
    doc.save("journal-entry.pdf");
  };

  // Filter entries based on search
  const filteredEntries = entries.filter(e =>
    e.text.toLowerCase().includes(search.toLowerCase()) ||
    e.tags.join(", ").toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="app-container">
      <header>
        <h1>Daily Prompt</h1>
        <button onClick={() => setDarkMode(!darkMode)}>
          {darkMode ? "☀️ Light Mode" : "🌙 Dark Mode"}
        </button>
      </header>

      <div className="tabs">
        <button
          className={selectedTab === "prompt" ? "active" : ""}
          onClick={() => setSelectedTab("prompt")}
        >
          New Entry
        </button>
        <button
          className={selectedTab === "entries" ? "active" : ""}
          onClick={() => setSelectedTab("entries")}
        >
          Past Entries
        </button>
      </div>

      {selectedTab === "prompt" && (
        <div className="prompt-section">
          <h2>{currentPrompt}</h2>
          <button onClick={() => setCurrentPrompt(prompts[Math.floor(Math.random() * prompts.length)])}>
            New Prompt 🎲
          </button>
          <textarea
            rows={6}
            value={entry}
            onChange={(e) => setEntry(e.target.value)}
            placeholder="Start writing here..."
          />
          <input
            type="text"
            placeholder="Tags (comma-separated)"
            value={tags}
            onChange={(e) => setTags(e.target.value)}
          />
          <button className="save-btn" onClick={handleSave}>
            {editingIndex !== null ? "Update Entry" : "Save Entry"}
          </button>
        </div>
      )}

      {selectedTab === "entries" && (
        <div className="entries-section">
          <input
            type="text"
            placeholder="Search entries or tags..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="search-input"
          />
          {filteredEntries.length === 0 ? (
            <p>No entries yet.</p>
          ) : (
            filteredEntries.map((entry, index) => (
              <div className="entry-card" key={index}>
                <div className="entry-header">
                  <strong>{entry.prompt}</strong>
                  <span>{entry.date}</span>
                </div>
                <p>{entry.text}</p>
                {entry.tags.length > 0 && (
                  <div className="tags">
                    {entry.tags.map((tag, i) => (
                      <span key={i} className="tag">{tag}</span>
                    ))}
                  </div>
                )}
                <div className="entry-buttons">
                  <button onClick={() => handleEdit(index)}>✏️ Edit</button>
                  <button onClick={() => handleDelete(index)}>🗑️ Delete</button>
                  <button onClick={() => handleDownload(entry)}>📄 Download</button>
                </div>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
};
export default App;